### ISSUE TITLE
Error when enabling addon

### ISSUE THREAD

**Issue by GlitchedByte** [Nusiq/mcblend#37] opened 2020-04-19 16:49 UTC
Hey, I downloaded the latest zip file (3.2.0) and installed it in blender. When I wanna enable the addon, I get this error:

![image](https://user-images.githubusercontent.com/40072014/79694241-6672c600-826f-11ea-8c0b-064ba02b69f3.png
)

**Comment by Nusiq** [comment] 2020-04-19 20:12
What is the Blender version that you use? 2.79?

The 2.80 blender update was quite a big change. I'm using specifically Blender 2.82a (which is currently the newest stable release). Blender 2.80 and anything above should _probably_ work.

**Comment by Nusiq** [comment] 2020-04-26 14:28
Judging by the screenshot this problem is related to blender 2.79. The error report shows syntax error on the type annotation. Type annotations were added to Python 3.5 so the version of blender that you use must be using something older. I'm closing the issue because I can't reproduce the error and I don't plan to support Blender 2.79.

**Closed by Nusiq** 2020-04-26 14:28 UTC
Labels: wontfix
